### PR TITLE
Redesigned Login Page as we agreed on by the figma design and updated some of the semantics

### PR DESCRIPTION
**Pull request by JustMax7CB**

### CODE REVIEW

**Comment by JustMax7CB** [comment]
[Login Page](https://trello.com/c/NM1GRhvZ/1-login-page)

**Comment by JustMax7CB** [comment]
[דף בית](https://trello.com/c/2QqeXFc9/5-%D7%93%D7%A3-%D7%91%D7%99%D7%AA)

**Comment by JustMax7CB** [comment]
[Register Page](https://trello.com/c/9hoRhoV3/2-register-page)

**Comment by JustMax7CB** [comment]
[Glucose Form Bottom Sheet](https://trello.com/c/hvZpxOHi/21-glucose-form-bottom-sheet)

**Review by Tali-hub — APPROVED** [review]

**Pull request merged**
